FROM eclipse-temurin:21.0.3_9-jdk


LABEL authors="Pietro"
LABEL manteiner="begear.it"


COPY target/E-commerce-0.0.1-SNAPSHOT.jar E-commerce-0.0.1-SNAPSHOT.jar


ENTRYPOINT ["java", "-jar", "E-commerce-0.0.1-SNAPSHOT.jar"]